import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/family/FamilyMemberCard.tsx
import NutrientCircle from "./NutrientCircle";
export default function FamilyMemberCard({ member }) {
    const avatarUrl = member.avatar
        ? member.avatar
        : `https://api.dicebear.com/9.x/identicon/svg?seed=${member.username}`;
    return (_jsxs("div", { className: "p-4 border rounded-lg shadow-md bg-white flex flex-col md:flex-row gap-4", children: [_jsx("div", { className: "flex justify-center items-center md:basis-[15%]", children: _jsx("img", { src: avatarUrl, className: "w-28 h-28 rounded-full object-cover border-2 border-gray-200" }) }), _jsxs("div", { className: "md:basis-[25%] max-h-36 overflow-y-auto px-2", children: [_jsx("p", { className: "text-lg font-semibold mb-1", children: member.fullname || member.username }), _jsxs("p", { className: "text-gray-500 text-sm mb-2", children: ["@", member.username] }), _jsxs("div", { className: "text-gray-600 text-sm space-y-1", children: [member.dob && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "DOB:" }), " ", member.dob] }), member.gender && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "Gender:" }), " ", member.gender] }), member.height && member.weight && (_jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "Height/Weight:" }), " ", member.height, " cm / ", member.weight, " kg"] })), member.bmi && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "BMI:" }), " ", member.bmi] }), member.activity_level && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "Activity:" }), " ", member.activity_level] }), member.disease && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "Disease:" }), " ", member.disease] }), member.allergen && _jsxs("p", { children: [_jsx("span", { className: "font-semibold", children: "Allergen:" }), " ", member.allergen] })] })] }), _jsxs("div", { className: "md:basis-[60%] grid grid-cols-2 sm:grid-cols-4 gap-3", children: [_jsx(NutrientCircle, { label: "Protein", value: member.eaten_protein || 0, goal: member.target_protein || 0, color: "#60a5fa" }), _jsx(NutrientCircle, { label: "Carb", value: member.eaten_carbs || 0, goal: member.target_carbs || 0, color: "#fbbf24" }), _jsx(NutrientCircle, { label: "Fat", value: member.eaten_fat || 0, goal: member.target_fat || 0, color: "#34d399" }), _jsx(NutrientCircle, { label: "Calories", value: member.eaten_calories || 0, goal: member.target_calories || 0, color: "#ef4444" })] })] }));
}
