import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { FiAlertCircle, FiUpload, FiLoader, FiSearch } from "react-icons/fi";
import { useScanAllergen } from "../hooks/ingredient_safety_hooks"; // <-- import hook
export default function IngredientSafetyPage() {
    const [selectedFile, setSelectedFile] = useState(null);
    const [ingredients, setIngredients] = useState(null);
    const { scanAllergen, loading, error } = useScanAllergen();
    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setSelectedFile(e.target.files[0]);
            setIngredients(null); // reset khi chọn ảnh mới
        }
    };
    const handleScan = async () => {
        if (!selectedFile)
            return;
        const result = await scanAllergen(selectedFile);
        setIngredients(result.map(name => ({ name })));
    };
    return (_jsx("div", { className: "container mx-auto px-4 py-6 pt-27", children: _jsxs("div", { className: "flex gap-6", children: [_jsxs("div", { className: "flex-1 bg-white p-6 rounded-lg shadow flex flex-col", children: [_jsx("h2", { className: "text-xl font-bold mb-2", children: "T\u1EA3i \u1EA3nh nguy\u00EAn li\u1EC7u" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Ch\u1ECDn \u1EA3nh nguy\u00EAn li\u1EC7u \u0111\u1EC3 qu\u00E9t th\u00E0nh ph\u1EA7n g\u00E2y d\u1ECB \u1EE9ng." }), _jsx("div", { className: "w-full h-62 bg-gray-100 rounded-lg border border-dashed relative flex items-center justify-center mb-4 overflow-hidden", children: selectedFile ? (_jsx("img", { src: URL.createObjectURL(selectedFile), alt: "Preview", className: "w-full h-full object-contain bg-black" })) : (_jsxs("label", { className: "flex flex-col items-center justify-center absolute inset-0 cursor-pointer", children: [_jsx(FiUpload, { className: "text-4xl mb-2 text-gray-500" }), _jsx("span", { className: "text-gray-700 font-semibold", children: "Ch\u1ECDn \u1EA3nh..." }), _jsx("input", { type: "file", accept: "image/*", onChange: handleFileChange, className: "hidden" })] })) }), _jsxs("div", { className: "w-full flex gap-4 mt-2", children: [_jsxs("label", { className: "flex-1 flex items-center justify-center gap-2 px-4 py-2 border-2 border-blue-600 text-blue-600 bg-white rounded-md cursor-pointer hover:bg-blue-600 hover:text-white transition", children: [_jsx(FiUpload, { className: "text-xl" }), _jsx("span", { className: "font-semibold", children: "Upload \u1EA3nh" }), _jsx("input", { type: "file", accept: "image/*", onChange: handleFileChange, className: "hidden" })] }), _jsxs("button", { onClick: handleScan, disabled: !selectedFile || loading, className: `flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-md font-semibold text-white transition cursor-pointer
                ${selectedFile && !loading ? "bg-blue-600 hover:bg-blue-800" : "bg-gray-400 cursor-not-allowed"}`, children: [_jsx(FiSearch, {}), _jsx("span", { children: loading ? "Đang quét..." : "Quét nguyên liệu" })] })] })] }), _jsxs("div", { className: "flex-2 bg-white p-6 rounded-lg shadow min-h-[300px] flex flex-col", children: [_jsx("h2", { className: "text-xl font-bold mb-2", children: "Nguy\u00EAn li\u1EC7u d\u1ECB \u1EE9ng" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Danh s\u00E1ch c\u00E1c nguy\u00EAn li\u1EC7u c\u00F3 th\u1EC3 g\u00E2y d\u1ECB \u1EE9ng v\u1EDBi ng\u01B0\u1EDDi d\u00F9ng d\u1EF1a tr\u00EAn \u1EA3nh \u0111\u00E3 qu\u00E9t." }), _jsx("div", { className: "flex-1 bg-gray-50 rounded p-4 overflow-y-auto", children: loading ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full", children: [_jsx(FiLoader, { className: "animate-spin text-5xl text-blue-500 mb-4" }), _jsx("p", { className: "text-lg font-semibold text-gray-600", children: "\u0110ang qu\u00E9t..." })] })) : error ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-red-500", children: [_jsx(FiAlertCircle, { className: "text-5xl mb-4" }), _jsx("p", { className: "text-lg font-semibold", children: error })] })) : ingredients === null ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-gray-500", children: [_jsx(FiAlertCircle, { className: "text-5xl mb-4" }), _jsx("p", { className: "text-lg font-semibold", children: "Ch\u01B0a qu\u00E9t nguy\u00EAn li\u1EC7u" })] })) : ingredients.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-green-500", children: [_jsx(FiAlertCircle, { className: "text-5xl mb-4" }), _jsx("p", { className: "text-lg font-semibold", children: "Kh\u00F4ng c\u00F3 nguy\u00EAn li\u1EC7u g\u00E2y d\u1ECB \u1EE9ng" })] })) : (_jsx("ul", { className: "list-disc pl-6 space-y-2 h-70 overflow-y-auto", children: ingredients.map((ing, idx) => (_jsx("li", { className: "text-gray-700 font-medium", children: ing.name }, idx))) })) })] })] }) }));
}
